# Site settings
#theme
theme: jekyll-theme-primer

#Site basics
title: "Technical Intelligence & Research"
description: "Exploring malware, vulnerabilities, and reverse engineering software to find out how it really works."
url: "https://mja-reversing.github.io"
baseurl: ""

# Author Info
author:
  name: "Matt Allan"
  bio: "Technical Security Researcher specializing in the intersection of malware internals and adversary intelligence."

# Navigation
navbar:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "Posts"
    url: "/posts"

# Markdown & Syntax Highlighting
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Blog Post Settings
permalink: /blog/:title/
paginate: 5
paginate_path: "/page:num/"

# Collections (lets you expand later)
collections:
  notes:
    output: true
    permalink: /notes/:path/

# Defaults (auto-apply layouts)
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclusions (files not published)
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
